doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Symfony\Infrastructure\Migrations': '%kernel.project_dir%/src/Symfony/Infrastructure/Migrations'
    enable_profiler: '%kernel.debug%'
