version: '3'
services:
  backend:
    container_name: backend
    user: "${USER_ID}:${GID}"
    build:
      context: ./back
      dockerfile: Dockerfile.local
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GID}
        - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ./back:/app
    networks:
      - rm_next
    command: symfony serve --port=8000
  database:
    container_name: database
    image: mariadb:10.7.3
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    ports:
      - 3500:3306
    networks:
      - rm_next
  frontend:
    container_name: frontend
    user: "${USER_ID}:${GID}"
    build:
      context: ./front
      dockerfile: Dockerfile.local
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GID}
        - PORT=5050
    ports:
      - 5000:5000
    volumes:
      - ./front:/app
    networks:
      - rm_next
networks:
  rm_next:
