---
profession_names:
  path: /profession/names
  controller: App\Character\Infrastructure\EntryPoint\Api\ProfessionNamesController::index
  methods: GET

profession_detail:
  path: /profession/{professionCode}
  controller: App\Character\Infrastructure\EntryPoint\Api\ProfessionController::getByCode
  methods: GET
