export enum CultureCode {
  DEEP_WARRENS = 'DEEP_WARRENS',
  NOMADIC = 'NOMADIC',
  RURAL = 'RURAL',
  SHALLOW_WARRENS = 'SHALLOW_WARRENS',
  SYLVAN = 'SYLVAN',
  UNDERHILL = 'UNDERHILL',
  URBAN = 'URBAN'
}
