services:
    App\User\Domain\UserRepository: '@App\User\Infrastructure\Persistence\InMemory\InMemoryUserRepository'
    test.userRepository:
        alias: App\User\Domain\UserRepository
        public: true
