services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\User\Domain\UserRepository: '@App\User\Infrastructure\Persistence\InMemory\InMemoryUserRepository'

  user.mailer:
    alias: App\User\Infrastructure\Mailer\SymfonyUserMailer
    public: true

  test.userRepository:
    alias: App\User\Domain\UserRepository
    public: true

  App\Tests\acceptance\context\:
    resource: '../tests/acceptance/context/*'
