services:
    App\User\Domain\UserRepository: '@App\User\Infrastructure\Persistence\InMemory\InMemoryUserRepository'
    test.userRepository:
        alias: App\User\Domain\UserRepository
        public: true

    test.eventStore:
        alias: App\Shared\Infrastructure\Event\DoctrineEventStore
        public: true
