FROM xbellon/sf-php_81:0.0.4

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG PORT=8000

EXPOSE ${PORT}

USER root
RUN usermod -u ${USER_ID} gfuser
RUN groupmod -g ${GROUP_ID} gfuser

WORKDIR /app

USER gfuser
ENV HOME /home/gfuser

RUN mkdir -p /home/gfuser/jwt
#COPY --chown=gfuser .docker/private.pem /home/gfuser/jwt
#COPY --chown=gfuser .docker/public.pem /home/gfuser/jwt

