FROM xbellon/sf-php_81:0.0.3

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG PORT=8000

EXPOSE ${PORT}

WORKDIR /app

RUN mkdir -p /home/gfuser/jwt
COPY .docker/private.pem /home/gfuser/jwt
COPY .docker/public.pem /home/gfuser/jwt

ENV HOME /home/gfuser
