#FROM node:14.18-alpine
FROM node:16.13.1-alpine

ARG PORT=5050

EXPOSE ${PORT}
ENV PORT=${PORT}

WORKDIR /app

COPY package.json .
COPY package-lock.json .

USER node
RUN npm install

# allow non-root users have home
RUN mkdir -p /opt/home
RUN chmod 777 /opt/home
ENV HOME /opt/home

CMD ["npm", "run", "dev"]
