when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
api_ready:
    path: /api/ready
    controller: App\Ready\Infrastructure\EntryPoint\Api\ReadyController::index
    methods: ['GET']

