---
name: PHP Composer
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iamsauravsharma/create-dotenv@v1.2.2
        with:
          file-name: '.env'  # Optional (default : '.env')
          directory: 'back/'  # Optional (default: '.')
        env:  # env available for only this steps
          DATABASE_URL: ''
          APP_ENV: env
          APP_SECRET: someVeryStrangeSecret
          FRONT_BASE_URL: http://localhost:5000
          JWT_PASSPHRASE: asdasdasdasdadasdadadasdasd
          MESSENGER_TRANSPORT_DSN: doctrine://default
      - name: Validate composer.json and composer.lock
        working-directory: ./back
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        working-directory: ./back
        run: composer install --prefer-dist --no-progress

# Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
# Docs: https://getcomposer.org/doc/articles/scripts.md

# - name: Run test suite
#   run: composer run-script test
